Workaround linking issue on OS X
This commit hides the extern templates declarations introduced by
3333e608 on non-Windows platforms.  I don't understand why linking
fails on OS X, but this should fix it for now.

Sample from the linker output:

  Linking CXX shared library ../../lib/libSofaVolumetricData.dylib
  Undefined symbols for architecture x86_64:
    "BarycentricContactMapper<TTriangleModel<Vec3dTypes, Vec3dTypes::createMapping(char const*)", referenced from:
        vtable for BarycentricContactMapper<TTriangleModel<Vec3dTypes, Vec3dTypes in BarycentricPenalityContact_DistanceGrid.cpp.o
    "BarycentricContactMapper<TTriangleModel<Vec3dTypes, Vec3dTypes::cleanup()", referenced from:
        vtable for BarycentricContactMapper<TTriangleModel<Vec3dTypes, Vec3dTypes in BarycentricPenalityContact_DistanceGrid.cpp.o
  ld: symbol(s) not found for architecture x86_64


Former-commit-id: a5412f5174dbbc2dc0472253327ca6942bead446